[package]
name = "learning_bevy"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["toy_prng", "pig"]

[workspace.dependencies]
bevy = "0.16"
bevy_egui = "0.34"
rand = "0.8"
pcg_rand = "0.13.0"
rand_xorshift = "0.3.0"